// Auto-generated by domain-i18n. Do not edit manually.

type DomainI18nKey =
  | never

declare module 'vue-i18n' {
  export interface DefineLocaleMessage {
    [key: DomainI18nKey]: string
  }
}

export type { DomainI18nKey }
